### ISSUE TITLE
Invalid processed dataset link

### ISSUE THREAD

**Issue by LivingXu** [turboLJY/Few-Shot-KG2Text#11]
Hi, the processed dataset on Google Drive is no longer accessible. Could you please update the valid version?

**Comment by turboLJY** [comment]
I have updated the google drive link. But I can only find the webnlg dataset. As for other two datasets, you can download them from their original link and process them using our code.

**Comment by LivingXu** [comment]
> I have updated the google drive link. But I can only find the webnlg dataset. As for other two datasets, you can download them from their original link and process them using our code.

Thx!
