### ISSUE TITLE
RBFS to traverse graph

### ISSUE THREAD

**Issue by Beakboomboom** [turboLJY/Few-Shot-KG2Text#3]
Hi, i am confused where is the part of using RBFS to linearized graph in the code, Can you please help me?

**Comment by turboLJY** [comment]
good question! At first, we indeed utilized RBFS, but later on, we found it time-consuming and not fit the end-to-end training. So, we took RBFS as a preprocessing step by using TransE.

**Comment by Beakboomboom** [comment]
Thank you for you reply~ and Where is the preprocessing RBFS in the code?  Is it in process.py?

**Comment by SakerLiu** [comment]
The code may exist some errors in RBFS and their data processing

**Comment by turboLJY** [comment]
We provide the code about RBFS based on the pretrained TransE embeddings.

**Comment by SakerLiu** [comment]
> We provide the code about RBFS based on the pretrained TransE embeddings.

Can you provide the pretrained TransE embeddings.
